project:
  type: website
  output-dir: public
  
website:
  title: Data visualization course
  page-footer:
    background: dark
    center:
      - text: "© Copyright Daniel Kapitan Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0), 2023"
  repo-url: https://github.com/dkapitan/data-viz-course
  repo-branch: master
  repo-actions: [edit, issue]
  sidebar:
    search: true
    # tools:
    #     - icon: github
    #       href: https://github.com/dkapitan/data-viz-course
    #       text: "https://github.com/dkapitan/data-viz-course"
    logo: altair-hist.png
    contents:
      - index.md
      - section: Altair
        contents:
          - docs/altair_introduction.ipynb
          - docs/altair_marks_encoding.ipynb
          - docs/altair_data_transformation.ipynb
          - docs/altair_scales_axes_legends.ipynb
          - docs/altair_view_composition.ipynb
          - docs/altair_interaction.ipynb
          - docs/altair_cartographic.ipynb
      - section: Support
        contents:
          - docs/altair_debugging.ipynb
toc: true
format:
  html:
    theme: zephyr
    code-link: true
execute:
  freeze: true

